/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { REC20 } from "./ERC20.sol/REC20";
export { REC20__factory } from "./factories/ERC20.sol/REC20__factory";
export { Lock__factory } from "./factories/Lock__factory";
